// <auto-generated />
using System;
using ExpenseSplitter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseSplitter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseSplitterDbContext))]
    [Migration("20260905185942_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(29, 2)
                        .HasColumnType("numeric(29,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PaidByParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaidByParticipantId");

                    b.HasIndex("TripId", "CreatedAt");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount", "\"Amount\" > 0 AND \"Amount\" <= 792281625142643375935439503.35");

                            t.HasCheckConstraint("CK_Expenses_SplitType", "\"SplitType\" IN (0)");
                        });
                });

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Expense", b =>
                {
                    b.HasOne("ExpenseSplitter.Domain.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("PaidByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExpenseSplitter.Domain.Entities.Trip", null)
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ExpenseSplitter.Domain.ValueObjects.ExpenseShare", "Shares", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(29, 2)
                                .HasColumnType("numeric(29,2)");

                            b1.HasKey("ExpenseId", "ParticipantId");

                            b1.HasIndex("ParticipantId");

                            b1.ToTable("ExpenseParticipants", null, t =>
                                {
                                    t.HasCheckConstraint("CK_ExpenseParticipants_Amount", "\"Amount\" >= 0 AND \"Amount\" <= 792281625142643375935439503.35");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");

                            b1.HasOne("ExpenseSplitter.Domain.Entities.Participant", null)
                                .WithMany()
                                .HasForeignKey("ParticipantId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();
                        });

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Participant", b =>
                {
                    b.HasOne("ExpenseSplitter.Domain.Entities.Trip", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseSplitter.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
