<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <Compile Include="../ExpenseSplitter.Infrastructure.Tests/PostgreSqlFixture.cs" Link="PostgreSqlFixture.cs" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/ExpenseSplitter.Api/ExpenseSplitter.Api.csproj" />
  </ItemGroup>
</Project>
